// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HttpGetter is an autogenerated mock type for the HttpGetter type
type HttpGetter struct {
	mock.Mock
}

type HttpGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpGetter) EXPECT() *HttpGetter_Expecter {
	return &HttpGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: url
func (_m *HttpGetter) Get(url string) (*http.Response, error) {
	ret := _m.Called(url)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HttpGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type HttpGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *HttpGetter_Expecter) Get(url interface{}) *HttpGetter_Get_Call {
	return &HttpGetter_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *HttpGetter_Get_Call) Run(run func(url string)) *HttpGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HttpGetter_Get_Call) Return(resp *http.Response, err error) *HttpGetter_Get_Call {
	_c.Call.Return(resp, err)
	return _c
}

type mockConstructorTestingTNewHttpGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewHttpGetter creates a new instance of HttpGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHttpGetter(t mockConstructorTestingTNewHttpGetter) *HttpGetter {
	mock := &HttpGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
